#pragma once
#include <Arduino.h>
#include "SPI.h"
#include <Robojax_L298N_DC_motor.h>
#include <ADNS3080.h>
#include <iostream>
#include "motor_control.h"
#include <MPU6050_light.h>
#include "Wire.h"
#include  <math.h>
